<?php // Get current product
$product = $block->getProduct();
$product->getId();
$categories = $product->getCategoryIds();
//print_r($categories);
//$mystring = implode(', ',$categories);
$andopration ='';
for($f=0;$f<count($categories);$f++){
if($andopration == ''){

$andopration = 'FIND_IN_SET('.$categories[$f].',categories) > 0 ';	
	
   }else{

$andopration = '('.$andopration.'OR FIND_IN_SET('.$categories[$f].',categories) > 0 )';	
	
 }
}

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $resource = $objectManager->create('Magento\Framework\App\ResourceConnection');
 $connection = $resource->getConnection('core_write');
 $table =  $connection->getTableName('dotsquares_filescollection_items');
// echo $QURY = 'SELECT * FROM ' . $table .' WHERE product_ids LIKE "%'.$product->getId().'%"';
$QURY = 'SELECT * FROM ' . $table .' WHERE status=1 AND FIND_IN_SET('.$product->getId().',product_ids) > 0 AND '. $andopration;
 //die();
 $productfiles = $connection->fetchAll($QURY);
 //print_r($productfiles);
 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$ffrt = $currentStore->getBaseUrl();

$defimagpath = $ffrt.'app/code/Dotsquares/FilesCollection/view/frontend/templates/Package-Download.PNG';

if(count($productfiles)<1){
	echo 'No attachment found.';
}

 foreach($productfiles as $files){
  $fileaccessURL = $mediaUrl.'dotsquares'.$files['file_name'];
   $mediaID = $files['id'];
   $medianame = $files['name'];    
  //print_r($files);
  /*file ewxten*/
  $ext = substr($files['file_name'], strrpos($files['file_name'], '.') + 1);

   if($ext == 'xlsx'){
	   
	   $passclass = "xlsx";
	   
   }else if($ext == 'pdf'){
	   
	   $passclass = "pdf";
	   
   }else if($ext == 'doc'){
	   
	   $passclass = "doc";
	   
   }else if($ext == 'docx'){
	   
	   $passclass = "doc";
	   
   }else if($ext == 'csv'){
	   
	   $passclass = "csv";
	   
   }else if($ext == 'zip'){
	   
	   $passclass = "zip";
	   
   }else if($ext == 'flv' || $ext == 'avi' || $ext == 'mov' || $ext == 'wmv' || $ext == '3gp' || $ext == 'mp4' || $ext == 'mp3'){
	   
	   $passclass = "video";
	   
   }else if($ext == 'jpg' || $ext == 'png' || $ext == 'bmp' || $ext == 'gif' || $ext == 'jpeg' ){
	   
	   $passclass = "img";
	   
   }else{
	   
	   $passclass = "packg";
	   
   }
   
  /*file ext end*/

    echo '<div class="downloadfile"><div class="upimag"><a href="'.$fileaccessURL.'" download><span class="filimag-'.$passclass.'"></span></a></div><div class="upname"><a href="'.$fileaccessURL.'" download>'.$medianame.'</a></div></div>';  
	
 }
 

?>
 
 
<h1 style="color: #ff5501">


<?php //echo $product->getData('Dotsquares'); ?>
</h1>